Bugfix/backward compatibility
js-accounts/graphql pull request #15
Opened 2017-07-25 07:25 UTC by dotansimha

- The recent changes by @tomermoshe caused the `user` field of `loginWithPassword` to be of typer `UserInput` instead `String`, causing the previous API to break and prevents users to login when using latest version.

This PR changes `user` argument to type `String` and added another optional input type for `UserInput`.

2017-07-25 08:15 UTC, tomermoshe commented on packages/graphql-api/src/resolvers/login-with-password.js
> +      return await Accounts.loginWithPassword(user, password);
you mean loginWithPassword(userInput, password)

2017-07-25 08:17 UTC, tomermoshe commented on packages/graphql-api/src/resolvers/login-with-password.js
> +    if (userInput) {
look at https://github.com/js-accounts/graphql/blob/master/packages/graphql-client/src/graphql-client.js#L70

userInput will always be undefined

2017-07-25 09:15 UTC, davidyaha requested changes

2017-07-25 09:15 UTC, davidyaha commented on packages/graphql-client/src/graphql-client.js
> +    return await this.mutate(loginMutation, 'loginWithPassword', { userInput: user, password });
`PasswordLoginUserIdentityType` could be either string or object

2017-11-04 14:08 UTC, davidyaha commented
Closed in favor of #19

2017-11-04 14:08 UTC, closed without merging